fix(tooling-api): project initialization failure when the project contains a Java library module
This happens due to the use of relocated packages in AndroidIDE's Java Compiler API. The 'JavaModuleCompilerSettings' class references the 'javax.lang.model.SourceVersion.RELEASE_11' enum.
However, in AndroidIDE, the SourceVersion class has the package name 'jdkx.lang.model'.

The project compiles successfully as the ':subprojects:tooling-api-model' module is a Java library due to which, 'javax.lang.model.SourceVersion' can be referenced without any errors.
However at runtime, there is no such class and hence the 'NoClassDefFoundError' is thrown. This exception is silently logged to the error stream by the JSONRpc protocol and hence it
cannot be seen in the IDE logs.

This closes #875.